### ISSUE TITLE
Generate the dataset error: chapter-02/01-full-load/01-full-loader-airflow-postgresql-data-exposition

### ISSUE THREAD

**Issue by javandres** [bartosz25/data-engineering-design-patterns-book#5]
An error occurred when trying to generate the dataset in [1. Generate the dataset](https://github.com/bartosz25/data-engineering-design-patterns-book/tree/master/chapter-02/01-full-load/01-full-loader-airflow-postgresql-data-exposition) step:

![image](https://github.com/user-attachments/assets/f5589d5c-8e79-4c4b-b2cf-3f956b47f4ba)

**Comment by bartosz25** [comment]
Hi @javandres 

Thank you for reporting the issue. I fixed this in https://github.com/bartosz25/data-engineering-design-patterns-book/commit/9276e656779c77cb3bf14b4457978491c2167664 . At the same time, I'll update the remaining 0.1 versions of the data-generator by the end of this week. Let's keep the issue open before I finish this upgrade.

**Comment by bartosz25** [comment]
Closing, as all is updated.
